apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: akshay
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      app: nginx
  replicas: 2